import type { Metadata } from "next";
import { Nunito, Anton } from "next/font/google";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

const anton = Anton({subsets: ["latin"],
weight: "400",
variable: "--font-anton",})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${anton.variable} bg-myyellow relative`}>{children}</body>
    </html>
  );
}
